name: Docker

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: false
        type: string
        default: "."
      IMAGE_NAME:
        required: false
        type: string
        default: ${{ github.repository }}
    secrets:
      DOCKER_PASSWORD:
        required: true
    outputs:
      image:
        description: "Output image with tags"
        value: ${{ jobs.push-image-to-registry.outputs.tags }}

jobs:
  push-image-to-registry:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: ./.github/actions/setvars

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ inputs.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.WORKING_DIRECTORY }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
