name: Lint and Test

on:
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm Install
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test-cypress
